Merge

diff --git a/ssh/local_command b/ssh/local_command
--- a/ssh/local_command
+++ b/ssh/local_command
@@ -53,19 +53,20 @@ mount_remote_fs()
 	fusermount -u $mnt_point >&$n || true
 	mkdir -p $mnt_point || { ssh_notify critical "Failed to create mount point \"$mnt_point\"." ; return ; }
 
-	# Login via localhost over control connection to ensure graceful shutdown of
-	# root-connection when disconnecting from host
-	local ssh_cmd="ssh -J $R"  # XXX: Remote port might become ambiguous here
-	ssh_cmd+=" -i $local_home/.ssh/hosts/$remote_hostname_cmd/id"
-	ssh_cmd+=" -o HostKeyAlias=ROOT-$R-$remote_port"
-	ssh_cmd+=" -o StrictHostKeyChecking=accept-new"
+	# # Login via localhost over control connection to ensure graceful shutdown of
+	# # root-connection when disconnecting from host
+	# local ssh_cmd="ssh -J $R"  # XXX: Remote port might become ambiguous here
+	# ssh_cmd+=" -i $local_home/.ssh/hosts/$remote_hostname_cmd/id"
+	# ssh_cmd+=" -o HostKeyAlias=ROOT-$R-$remote_port"
+	# ssh_cmd+=" -o StrictHostKeyChecking=accept-new"
 
-	ssh_notify low "ssh_cmd = $ssh_cmd"
+	# ssh_notify low "ssh_cmd = $ssh_cmd"
 
-	o=$( sshfs $=sshfs_opts -o ssh_command="$ssh_cmd" root@localhost:/ $mnt_point ) ||
-		{ ssh_notify critical "sshfs failed for root: err = $?, output = \"$o\"" ; return ; }
+	# o=$( sshfs $=sshfs_opts -o ssh_command="$ssh_cmd" root@localhost:/ $mnt_point ) ||
+	# 	{ ssh_notify critical "sshfs failed for root: err = $?, output = \"$o\"" ; return ; }
 
-	ssh_notify low "Successfully mounted sshfs as root."
+	# ssh_notify low "Successfully mounted sshfs as root."
+	
 }
 
 connect_tun()
@@ -111,9 +112,10 @@ uncloak_control_path()
 
 main()
 {
-	ssh_notify low "LocalCommand: $@ ($#@) debug=\"$SSH_DEBUG\""
+	ssh_notify low "LocalCommand: $@ ($#@) debug=\"$SSH_DEBUG\" $(pstree -ps $$)"
 	(( $#@ >= 11 )) || return
 
+	# Read ssh tokens from command line
 	C_hash=$1                 # %C
 	local_home=$2             # %d
 	remote_hostname=$3        # %h
@@ -126,25 +128,29 @@ main()
 	local_tuntap=$9; shift    # %T
 	local_username=$9         # %u
 
+	ssh_notify low "LocalCommand: parsed cmd_line"
+
 	# TODO: Check if adding '-p $remote_port' makes sense...
 	R="$remote_username@$remote_hostname_cmd"
 	tail -1 $ssh_history | read date time host 
 	[[ $host = $R:$remote_port ]] || {
 		echo "$(date '+%F %T') $R:$remote_port" >> $ssh_history
 		ssh_notify low "Updated ssh host history with $R:$remote_port." 
-	echo "$(date '+%F %T') $R:$remote_port" >> ~/.ssh/host_history; ssh_notify low "Updated ssh host history." 
+	}
 
-	sleep 0.3
+	sleep 1.3
+	ssh_notify low "LocalCommand: checking multiplex"
 	o=$( ssh -o BatchMode=yes -O check $R -p $remote_port 2>&1 ) ||
 		{ ssh_notify critical "Connection failed to multiplex: \"${(q)o//[[:cntrl:]]/}\"" ; return 1 ; }
 	ssh_notify normal "Connection multiplex: \"${o//[[:cntrl:]]/}\"" ; 
 
 	uncloak_control_path
 	check_remote_clock
-	$ssh_no_mount || mount_remote_fs
+	# $ssh_no_mount || mount_remote_fs
+	mount_remote_fs
 	connect_tun
 
-	sleep 2
+	sleep 9
 }
 
 main $@
