ssh: unify sshfs mountpoints

diff --git a/ssh/local_command b/ssh/local_command
--- a/ssh/local_command
+++ b/ssh/local_command
@@ -41,17 +41,17 @@ mount_remote_fs()
 	type sshfs >$n || { ssh_notify normal "sshfs not available."; return ; }
 
 	local sshfs_opts="-o compression=yes -o idmap=user -o transform_symlinks"
-	local mnt_point="$local_home/mnt/$remote_hostname_cmd"
+	local mnt_point="$local_home/mnt/SSHFS/$remote_hostname_cmd"
 	fusermount -u $mnt_point >&$n || true
 	mkdir -p $mnt_point || { ssh_notify critical "Failed to create mount point \"$mnt_point\"." ; return ; }
 	sshfs $=sshfs_opts -p $remote_port $R:/ $mnt_point || { ssh_notify critical "sshfs failed to mount." ; return ; }
 	ssh_notify low "Successfully mounted sshfs at $mnt_point."
 
 	# Create second mount point with root access - if possible
-	[[ $remote_username != "root" || $( ssh $R sudo id -u ) = 0 ]] || return  # Already mounted as root or no sudo
-	mnt_point=$mnt_point-ROOT
-	fusermount -u $mnt_point >&$n || true
-	mkdir -p $mnt_point || { ssh_notify critical "Failed to create mount point \"$mnt_point\"." ; return ; }
+	# [[ $remote_username != "root" || $( ssh $R sudo id -u ) = 0 ]] || return  # Already mounted as root or no sudo
+	# mnt_point=$mnt_point-ROOT
+	# fusermount -u $mnt_point >&$n || true
+	# mkdir -p $mnt_point || { ssh_notify critical "Failed to create mount point \"$mnt_point\"." ; return ; }
 
 	# # Login via localhost over control connection to ensure graceful shutdown of
 	# # root-connection when disconnecting from host
